import { useEffect, useRef, useState } from "react";
import { IMAGES } from "../lib/image-manifest";
import { cn } from "../utils/cn";

type AssetName = keyof typeof IMAGES;

/**
 * Responsive `picture` for the generated HAYA asset set.
 *
 * - Serves AVIF, falling back to WebP (both generated by scripts/optimize-images.mjs).
 * - Uses `sizes` so the browser downloads the smallest sufficient variant.
 * - Ships a ~20px inline LQIP as a blurred backdrop, so imagery paints
 *   immediately with zero layout shift while the real variant decodes.
 *
 * Migration note: the source art has no alpha, so the original `img-cutout`
 * multiply/mask treatment is preserved via the `className` passthrough.
 */
export function ResponsiveImage({
  name,
  alt,
  sizes,
  className,
  imgClassName,
  priority = false,
  /** Rendered width:height box, used to reserve space and avoid CLS. */
  ratio,
}: {
  name: AssetName;
  alt: string;
  /** CSS `sizes` hint describing rendered width at each breakpoint. */
  sizes: string;
  className?: string;
  imgClassName?: string;
  /** Set on the hero image only: eager + high fetch priority. */
  priority?: boolean;
  /** e.g. "1 / 1", "4 / 3", "16 / 11". Defaults to the source aspect. */
  ratio?: string;
}) {
  const asset = IMAGES[name];
  const [loaded, setLoaded] = useState(false);
  const imgRef = useRef<HTMLImageElement>(null);

  useEffect(() => {
    if (imgRef.current?.complete) {
      setLoaded(true);
    }
  }, []);

  const aspect = ratio ?? `${asset.width} / ${asset.height}`;
  const srcSet = (ext: string) =>
    asset.widths.map((w) => `/images/gen/${name}-${w}.${ext} ${w}w`).join(", ");

  return (
    <span
      className={cn("relative block overflow-hidden", className)}
      style={{ aspectRatio: aspect }}
    >
      {/* Blur-up placeholder — inlined, so it renders before any network fetch. */}
      <img
        src={asset.lqip}
        alt=""
        aria-hidden
        className={cn(
          "absolute inset-0 size-full scale-105 object-cover blur-xl transition-opacity duration-700",
          loaded ? "opacity-0" : "opacity-100"
        )}
      />
      <picture>
        <source type="image/avif" srcSet={srcSet("avif")} sizes={sizes} />
        <source type="image/webp" srcSet={srcSet("webp")} sizes={sizes} />
        <img
          ref={imgRef}
          src={`/images/gen/${name}-1024.webp`}
          alt={alt}
          width={asset.width}
          height={asset.height}
          sizes={sizes}
          loading={priority ? "eager" : "lazy"}
          decoding={priority ? "sync" : "async"}
          fetchPriority={priority ? "high" : "auto"}
          onLoad={() => setLoaded(true)}
          className={cn(
            "absolute inset-0 size-full transition-opacity duration-700",
            loaded ? "opacity-100" : "opacity-0",
            imgClassName
          )}
        />
      </picture>
    </span>
  );
}
